import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Fix Messy",
  description:
    "Fix Messy terms of service: acceptable use, AI-generated results, gallery consent, and shopping-list estimates.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <main>
      <h1 className="page-title">Terms of Service</h1>
      <p className="gallery-sub">Last updated: October 2026</p>

      <div className="card">
        <h3>1. What Fix Messy does</h3>
        <p className="guide">
          Fix Messy is a space-management web app. Upload a photo of a messy
          space and receive an AI-reorganized or AI-styled version of the
          image, a practical step-by-step guide, and a shopping list of
          suggested organizing products.
        </p>
      </div>

      <div className="card">
        <h3>2. AI-generated results</h3>
        <p className="guide">
          Before/after images, guides, product suggestions, and prices are
          generated by artificial intelligence and are illustrative estimates,
          not professional organizing, design, or financial advice. Results may
          be inaccurate or incomplete. Product prices and availability change;
          always confirm on the retailer&apos;s site before buying.
        </p>
      </div>

      <div className="card">
        <h3>3. Your photos</h3>
        <p className="guide">
          Only upload photos you own or have the right to share. If you tap
          &ldquo;Yes, Share,&rdquo; your before/after pair may be displayed
          publicly in the Photo Gallery. If you tap &ldquo;No Thanks,&rdquo;
          your photo is never uploaded or stored. Do not upload photos
          containing other people without their permission, or any unlawful
          content.
        </p>
      </div>

      <div className="card">
        <h3>4. Shopping links</h3>
        <p className="guide">
          &ldquo;Buy now&rdquo; buttons lead to third-party retailers. Fix
          Messy is not responsible for those sites, their prices, products, or
          fulfillment.
        </p>
      </div>

      <div className="card">
        <h3>5. Acceptable use</h3>
        <p className="guide">
          You agree not to misuse the service, attempt to disrupt it, or upload
          content that is unlawful, infringing, or harmful. We may remove
          gallery content or restrict access for violations.
        </p>
      </div>

      <div className="card">
        <h3>6. No warranty</h3>
        <p className="guide">
          The service is provided &ldquo;as is&rdquo; without warranties of any
          kind. We may modify or discontinue features at any time.
        </p>
      </div>
    </main>
  );
}
